version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  server:
    image: todo
    ports:
      - 4000:4000
    environment:
      DB_CONN_STRING: 'mongodb://admin:admin@mongo:27017'
      DB_NAME: 'todo'
